apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: talos-alloy-102
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    services:
      cidrBlocks:
        - 172.26.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: talos-alloy-102-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: PacketCluster
    name: talos-alloy-102
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: talos-alloy-102
    pool: worker-pool
  name: talos-alloy-102-worker
  namespace: default
spec:
  clusterName: talos-alloy-102
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: talos-alloy-102
      pool: worker-pool
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: talos-alloy-102
        pool: worker-pool
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: talos-alloy-102-worker
      clusterName: talos-alloy-102
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: PacketMachineTemplate
        name: talos-alloy-102-worker
      version: 1.26.1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PacketCluster
metadata:
  name: talos-alloy-102
  namespace: default
spec:
  facility: sk2
  projectID: REDACTED
  vipManager: CPEM
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PacketMachineTemplate
metadata:
  name: talos-alloy-102-control-plane
  namespace: default
spec:
  template:
    spec:
      billingCycle: hourly
      machineType: m3.small.x86
      os: talos_v1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PacketMachineTemplate
metadata:
  name: talos-alloy-102-worker
  namespace: default
spec:
  template:
    spec:
      billingCycle: hourly
      machineType: m3.small.x86
      os: talos_v1
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: talos-alloy-102-worker
  namespace: default
spec:
  template:
    spec:
      generateType: none
      talosVersion: v1.3.5
      data: |
        #!talos
        version: v1alpha1
        debug: false
        persist: true
        machine:
          type: worker
          token: REDACTED
          ca:
            crt: REDACTED
            key: ""
          certSANs: []
          kubelet:
            image: ghcr.io/siderolabs/kubelet:v1.26.1
            defaultRuntimeSeccompProfileEnabled: true
            disableManifestsDirectory: true
            extraArgs:
              cloud-provider: external
          network: {}
          install:
            disk: /dev/sda
            image: ghcr.io/siderolabs/installer:v1.3.3
            bootloader: true
            wipe: false
          registries: {}
          features:
            rbac: true
            stableHostname: true
            apidCheckExtKeyUsage: true
        cluster:
          id: REDACTED
          secret: REDACTED
          controlPlane:
            endpoint: https://REDACTED:6443
          network:
            dnsDomain: cluster.local
            podSubnets:
              - 10.244.0.0/16
            serviceSubnets:
              - 10.96.0.0/12
            cni:
              name: custom
              urls:
                - https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml
          token: REDACTED
          ca:
            crt: REDACTED
            key: ""
          discovery:
            enabled: true
            registries:
              kubernetes:
                disabled: true
              service: {}
          externalCloudProvider:
            enabled: true
            manifests:
              - https://github.com/equinix/cloud-provider-equinix-metal/releases/download/v3.6.0/deployment.yaml
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-alloy-102-control-plane
  namespace: default
spec:
  controlPlaneConfig:
    controlplane:
      generateType: none
      talosVersion: v1.3.5
      data: |
        #!talos
        version: v1alpha1
        debug: false
        persist: true
        machine:
          type: controlplane
          token: REDACTED
          ca:
            crt: REDACTED
            key: REDACTED
          certSANs: []
          kubelet:
            image: ghcr.io/siderolabs/kubelet:v1.26.1
            defaultRuntimeSeccompProfileEnabled: true
            disableManifestsDirectory: true
            extraArgs:
              cloud-provider: external
          network:
            interfaces:
              - interface: eth3
                vip:
                  ip: REDACTED
                  equinixMetal:
                    apiToken: REDACTED
          install:
            disk: /dev/sda
            image: ghcr.io/siderolabs/installer:v1.3.3
            bootloader: true
            wipe: false
          registries: {}
          features:
            rbac: true
            stableHostname: true
            apidCheckExtKeyUsage: true
        cluster:
          id: REDACTED
          secret: REDACTED
          controlPlane:
            endpoint: https://REDACTED:6443
          clusterName: talos-alloy-102
          network:
            dnsDomain: cluster.local
            podSubnets:
              - 10.244.0.0/16
            serviceSubnets:
              - 10.96.0.0/12
            cni:
              name: custom
              urls:
                - https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/calico.yaml
          token: REDACTED
          secretboxEncryptionSecret: REDACTED
          ca:
            crt: REDACTED
            key: REDACTED
          aggregatorCA:
            crt: REDACTED
            key: REDACTED
          serviceAccount:
            key: REDACTED
          apiServer:
            image: registry.k8s.io/kube-apiserver:v1.26.1
            certSANs:
              - REDACTED
            disablePodSecurityPolicy: true
            admissionControl:
              - name: PodSecurity
                configuration:
                  apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                  defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                  exemptions:
                    namespaces:
                      - kube-system
                    runtimeClasses: []
                    usernames: []
                  kind: PodSecurityConfiguration
            auditPolicy:
              apiVersion: audit.k8s.io/v1
              kind: Policy
              rules:
                - level: Metadata
            extraArgs:
              cloud-provider: external
          controllerManager:
            image: registry.k8s.io/kube-controller-manager:v1.26.1
            extraArgs:
              cloud-provider: external
          proxy:
            image: registry.k8s.io/kube-proxy:v1.26.1
          scheduler:
            image: registry.k8s.io/kube-scheduler:v1.26.1
          discovery:
            enabled: true
            registries:
              kubernetes:
                disabled: true
              service: {}
          etcd:
            ca:
              crt: REDACTED
              key: REDACTED
          extraManifests: []
          inlineManifests:
            - name: cpem-secret
              contents: |
                apiVersion: v1
                data:
                  cloud-sa.json: REDACTED
                kind: Secret
                metadata:
                  name: metal-cloud-config
                  namespace: kube-system
          externalCloudProvider:
            enabled: true
            manifests:
              - https://github.com/equinix/cloud-provider-equinix-metal/releases/download/v3.6.0/deployment.yaml
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: PacketMachineTemplate
    name: talos-alloy-102-control-plane
  replicas: 1
  version: v1.26.1
