apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  namespace: observability
  labels:
    team: rook
spec:
  namespaceSelector:
    matchNames:
      - storage
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: storage
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 5s