---
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: {{ .Values.multisite.realm_name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: {{ .Values.multisite.zone_group_name }}
  namespace: {{ .Release.Namespace }}
spec:
  realm: {{ .Values.multisite.realm_name }}
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: {{ .Values.multisite.zone_name }}
  namespace: {{ .Release.Namespace }}
spec:
  zoneGroup: {{ .Values.multisite.zone_group_name }}
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
  # recommended to set this value if ingress used for exposing rgw endpoints
  # customEndpoints:
  #   - "http://rgw-a.fqdn"
  #   - "http://rgw-b.fqdn"
  # if the pools need to be removed from backend enable following setting
  # preservePoolsOnDelete: false
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: multisite-{{ .Values.multisite.object_store_name }}
  namespace: {{ .Release.Namespace }}
spec:
  gateway:
    port: 80
    # securePort: 443
    instances: 1
  zone:
    name: {{ .Values.multisite.zone_name }}