{{- if $.Values.multisite.enabled }}
{{- range $.Values.multisite.applications }}
---
apiVersion: ceph.rook.io/v1
kind: CephObjectRealm
metadata:
  name: {{ .realm_name }}
  namespace: {{ $.Release.Namespace }}
{{- if .master_zone.defined }}
spec:
  pull:
    endpoint: http://rook-ceph-rgw-m-{{ .master_zone.name }}.storage
{{- end }}
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZoneGroup
metadata:
  name: {{ .zone_group_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  realm: {{ .realm_name }}
---
apiVersion: ceph.rook.io/v1
kind: CephObjectZone
metadata:
  name: {{ .zone_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  zoneGroup: {{ .zone_group_name }}
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: true
    parameters:
      compression_mode: none
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: m-{{ .object_store_name }}
  namespace: {{ $.Release.Namespace }}
spec:
  gateway:
    port: 80
    instances: 3
  zone:
    name: {{ .zone_name }}

{{- range .remaining_satellite_names }}
---
apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-m-{{ . }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    io.cilium/global-service: 'true'
    service.cilium.io/affinity: 'remote'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: rook-ceph-rgw
    ceph_daemon_id: m-{{ . }}
    rgw: m-{{ . }}
    rook_cluster: storage
    rook_object_store: m-{{ . }}
{{- end }}

{{- end}}
{{- end}}
