apiVersion: v2
name: istio-istiod
description: Opinionated deployment of istio

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: istiod
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.18.1