metallb:
  crds:
    enabled: true
cilium:
  socketLB: # istio https://docs.cilium.io/en/stable/network/istio/#setup-cilium
    enabled: true
    hostNamespaceOnly: true
  k8sServiceHost: {{ k8s_service_host }}
  k8sServicePort: {{ k8s_service_port }}
  cluster:
    name: {{ cluster_name }}
    id: {{ cluster_id }}
  tls:
    ca:
      cert: {{ ca_crt }}
      key: {{ ca_key }}
  ipam:
    mode: kubernetes
  kubeProxyReplacement: strict
  securityContext:
    privileged: true # ToDo: false | https://github.com/cilium/cilium/issues/21603#issuecomment-1453753820
  cgroup:
    autoMount:
      enabled: false
      hostRoot: /sys/fs/cgroup
  enableXTSocketFallback: false
  MTU: 1500
  hubble:
    enabled: true
    peerService:
      clusterDomain: {{ hubble_cluster_domain }}
    metrics:
      enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
    relay:
      enabled: true
    ui:
      enabled: true
  bpf:
    masquerade: true
  encryption:
    enabled: false # secret "cilium-ipsec-keys" not found
  hostFirewall:
    enabled: true
  policyEnforcementMode: always
  policyAuditMode: true # ToDo: Set to false
  ipv4NativeRoutingCIDR: 10.0.0.0/8
  externalWorkloads:
    enabled: true
  clustermesh:
    useAPIServer: true
    apiserver:
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/address-pool: mesh-public-ipv4
      replicas: 2