apiVersion: v2
name: nginx
description: Opinionated deployment of ingress-nginx

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: ingress-nginx
    version: 4.6.1
    repository: https://kubernetes.github.io/ingress-nginx
