apiVersion: v2
name: observability
description: configures kube-prometheus-stack

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: kube-prometheus-stack
    version: 51.0.3
    repository: https://prometheus-community.github.io/helm-charts