jaeger:
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-gcp
        external-dns.alpha.kubernetes.io/hostname: {{ jaeger_fqdn }}
        nginx.ingress.kubernetes.io/auth-url: https://{{ oauth_fqdn }}/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://{{ oauth_fqdn }}/oauth2/start
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
      hosts:
        - {{ jaeger_fqdn }}
      tls:
        - secretName: tls.{{ jaeger_fqdn }}
          hosts:
            - {{ jaeger_fqdn }}
  storage:
    type: none
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false
grafana:
  adminUser: {{ admin_user }}
  adminPassword: {{ admin_pass }}
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-gcp
      external-dns.alpha.kubernetes.io/hostname: {{ grafana_fqdn }}
      nginx.ingress.kubernetes.io/auth-url: https://{{ oauth_fqdn }}/oauth2/auth
      nginx.ingress.kubernetes.io/auth-signin: https://{{ oauth_fqdn }}/oauth2/start
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
    hosts:
      - {{ grafana_fqdn }}
    tls:
      - secretName: tls.{{ grafana_fqdn }}
        hosts:
          - {{ grafana_fqdn }}
victoria-metrics-cluster:
  clusterDomainSuffix: {{ cluster_name }}
  vmstorage:
    persistentVolume:
      storageClass: ceph-block
opentelemetry-collector:
  mode: daemonset
