rook-ceph-cluster:
  operatorNamespace: {{ operator_namespace }}
  clusterName: {{ cluster_name }}-rook
  cephClusterSpec:
    placement:
      all:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux # ToDo: set proper labels on nodes -> nodeLabels - https://www.talos.dev/v1.4/reference/configuration/#machineconfig
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
