apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data-volume
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ceph-block
