config:
  local_fqdn: {{ local_fqdn }}
harbor:
  logLevel: debug
  externalURL: https://{{ global_fqdn }}
  expose:
    type: ingress
    tls:
      enabled: true
      certSource: secret
      secret:
        secretName: tls.core.{{ global_fqdn }}
        notarySecretName: tls.notary.{{ global_fqdn }}
    ingress:
      hosts:
        core: {{ global_fqdn }}
        notary: notary.{{ global_fqdn }}
      className: nginx-global
      harbor:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-gcp
          external-dns.alpha.kubernetes.io/hostname: {{ global_fqdn }}
      notary:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-gcp
          external-dns.alpha.kubernetes.io/hostname: notary.{{ global_fqdn }}
    clusterIP:
      annotations:
        io.cilium/global-service: 'false'
        service.cilium.io/affinity: "local"
  persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        storageClass: ceph-block
        size: 100Gi
      chartmuseum:
        storageClass: ceph-block
      jobservice:
        jobLog:
          storageClass: ceph-block
      database:
        storageClass: ceph-block
      redis:
        storageClass: ceph-block
      trivy:
        storageClass: ceph-block
    imageChartStorage:
      disableredirect: true
      type: s3
      s3:
        region: {{ region }}
        bucket: {{ bucket }}
        accesskey: {{ accesskey }}
        secretkey: {{ secretkey }}
        regionendpoint: {{ regionendpoint }}

  database:
    type: external # ToDo: https://github.com/goharbor/harbor/issues/8649
    external:
      host: {{ db_host }} # It has to be PostgreSQL, CockroachDB does not work ;(
      port: {{ db_port }}
      username: {{ harbor['db']['user'] }}
      password: {{ harbor['db']['pass'] }}
      coreDatabase: {{ db_harbor_registry }}
      notaryServerDatabase: {{ db_harbor_notary_server }}
      notarySignerDatabase: {{ db_harbor_notary_signer }}
  harborAdminPassword: {{ harbor['admin_pass'] }}
  secretKey: {{ harbor['secret_key'] }}
  registry:
    credentials:
      username: {{ harbor['registry']['user'] }}
      password: {{ harbor['registry']['pass'] }}