config:
  local_fqdn: {{ local_fqdn }}
harbor:
  logLevel: debug
  externalURL: https://{{ global_fqdn }}
  expose:
    type: ingress
    tls:
      enabled: true
      certSource: secret
      secret:
        secretName: tls.core.{{ global_fqdn }}
        notarySecretName: tls.notary.{{ global_fqdn }}
    ingress:
      hosts:
        core: {{ global_fqdn }}
        notary: notary.{{ global_fqdn }}
      className: nginx-global
      harbor:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-gcp
          external-dns.alpha.kubernetes.io/hostname: {{ global_fqdn }}
      notary:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-gcp
          external-dns.alpha.kubernetes.io/hostname: notary.{{ global_fqdn }}
    clusterIP:
      annotations:
        io.cilium/global-service: 'false'
        service.cilium.io/affinity: "local"
  persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        storageClass: ceph-block
        size: 100Gi
      chartmuseum:
        storageClass: ceph-block
      jobservice:
        jobLog:
          storageClass: ceph-block
      database:
        storageClass: ceph-block
      redis:
        storageClass: ceph-block
      trivy:
        storageClass: ceph-block
  harborAdminPassword: {{ admin_pass }}
  secretKey: {{ secret_key }}
  registry:
    credentials:
      username: {{ registry.user }}
      password: {{ registry.pass }}