nexus:
  registries:
    - name: docker
      port: 9090
  ingressClassName: nginx-global
  fqdn: {{ fqdn }}
  oauth:
    fqdn: {{ oauth_fqdn }}
  db_name: {{ db_name }}
  db_user: {{ sonatype['db']['user'] }}
  db_pass: {{ sonatype['db']['pass'] }}
  admin_pass: {{ sonatype['nexus']['admin_pass'] }}
  s3:
    bucket: {{ bucket }}
    region: {{ regionendpoint }}
    accessKeyId: {{ accesskey }}
    sessionToken: {{ secretkey }}