keydb:
  persistentVolume:
    storageClass: ceph-block
cockroachdb:
  enabled: true
  clusterDomain: {{ cluster_domain }}
  conf:
    cluster-name: {{ cluster_name }}
    locality: cluster={{ locality }}
    join:
      - dbs-cockroachdb-0.dbs-cockroachdb.dbs.svc.titan.local:26257
      - dbs-cockroachdb-1.dbs-cockroachdb.dbs.svc.titan.local:26257
      - dbs-cockroachdb-2.dbs-cockroachdb.dbs.svc.titan.local:26257
{#      - dbs-cockroachdb-0.dbs-cockroachdb.dbs.svc.rhea.local:26257#}
{#      - dbs-cockroachdb-1.dbs-cockroachdb.dbs.svc.rhea.local:26257#}
{#      - dbs-cockroachdb-2.dbs-cockroachdb.dbs.svc.rhea.local:26257#}
  storage:
    persistentVolume:
      storageClass: ceph-block
  init:
    provisioning:
      enabled: true
      users:
        - name: {{ cockroachdb.username }}
          password: {{ cockroachdb.password }}
          options:
            - LOGIN
  tls:
    enabled: false
    certs:
      tlsSecret: true
      selfSigner:
        enabled: false
      certManager: true
      useCertManagerV1CRDs: true
      certManagerIssuer:
        group: cert-manager.io
        kind: ClusterIssuer
        name: {{ ca_issuer_name }}

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-gcp
      external-dns.alpha.kubernetes.io/hostname: {{ cockroach_fqdn }}
      nginx.ingress.kubernetes.io/auth-url: https://{{ oauth_fqdn }}/oauth2/auth
      nginx.ingress.kubernetes.io/auth-signin: https://{{ oauth_fqdn }}/oauth2/start
      nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/server-snippet: |
        proxy_ssl_verify off;
    hosts:
      - {{ cockroach_fqdn }}
    tls:
      - hosts:
        - {{ cockroach_fqdn }}
        secretName: tls.{{ cockroach_fqdn }}