postgres:
  cluster_name: {{ cluster_name }}
  replica:
    enabled: {{ replica_enabled }}
    primary_name: {{ primary_name }}
  external_clusters:
    {% for cluster in external_clusters %}
    - name: {{ cluster.name }}
    {% endfor %}