artifactory:
  splitServicesToContainers: false
  ingress:
    enabled: true
    defaultBackend:
      enabled: true
    hosts:
      - {{ fqdn }}
    routerPath: /
    artifactoryPath: /artifactory/
    className: "nginx-global"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-gcp
      external-dns.alpha.kubernetes.io/hostname: {{ fqdn }}
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    labels:
      traffic-type: external
    tls:
      - secretName: tls.{{ fqdn }}
        hosts:
          - {{ fqdn }}
  global:
    masterKey: {{ jfrog['artifactory']['master_key'] }}
    joinKey: {{ jfrog['artifactory']['join_key'] }}
  serviceAccount:
    create: true
  nginx:
    enabled: false
  artifactory:
    admin:
      ip: {{ jfrog['artifactory']['ip'] }}
      username: {{ jfrog['artifactory']['admin_user'] }}
      password: {{ jfrog['artifactory']['admin_pass'] }}
    persistence:
      enabled: true
      #existingClaim: artifactory-data-volume
      type: aws-s3-v3
      awsS3V3:
        bucketName: artifactory-bucket-bbdf4133-6b5a-40b4-b12b-309e080fd82e
        endpoint: rook-ceph-rgw-m-titan-artifactory.storage.svc
        useHttp: true
        credential: artifactory-bucket
        enablePathStyleAccess: true
    database:
      maxOpenConnections: 150
    tomcat:
      connector:
        maxThreads: 300
    resources:
      requests:
        memory: "6Gi"
        cpu: "2"
      limits:
        memory: "10Gi"
        cpu: "8"
    javaOpts:
      xms: "8g"
      xmx: "10g"
  access:
    database:
      maxOpenConnections: 150
    tomcat:
      connector:
        maxThreads: 100
  router:
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1"
  frontend:
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1"
  metadata:
    database:
      maxOpenConnections: 150
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1"
  event:
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1"
  jfconnect:
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1"
  integration:
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1"
  observability:
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "1"
  postgresql:
    enabled: false
  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: {{ db_url }}
    user: {{ jfrog['db']['user'] }}
    password: {{ jfrog['db']['pass'] }}