cert-manager:
  installCRDs: true
  serviceAccount:
    name: cert-manager
  global:
    leaderElection:
      namespace: "dns-tls"
external_dns:
  version: v0.13.4
  provider:
    google:
      enabled: true
      google_project: {{ google_project }}
      domain_filter: {{ domain_filter }}