argo-cd:
  dex:
    enabled: false
  configs:
    repositories:
      gitea:
        url: http://gitea-http.gitea:3000/gocy/{{ constellation_name }}.git
    cm:
      url: https://{{ argocd_fqdn }}
      oidc.config: |
        name: dex
        issuer: https://{{ bouncer_fqdn }}
        clientID: argocd
        clientSecret: {{ client_secret }}
        requestedScopes: ["openid", "profile", "email", "groups"]
      params:
        server.insecure: true
    rbac:
      policy.csv: |
        p, role:org-admin, applications, *, */*, allow
        p, role:org-admin, clusters, get, *, allow
        p, role:org-admin, repositories, *, *, allow
        p, role:org-admin, logs, get, *, allow
        p, role:org-admin, exec, create, */*, allow
        g, gocloudyourself:Dream, role:org-admin

  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-gcp
        external-dns.alpha.kubernetes.io/hostname: {{ argocd_fqdn }}
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/server-snippet: |
          proxy_ssl_verify off;
      ingressClassName: "nginx"
      hosts:
        - {{ argocd_fqdn }}
      tls:
        - secretName: tls.{{ argocd_fqdn }}
          hosts:
            - {{ argocd_fqdn }}
