{{- range .Values.role_bindings.admins }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc:{{.provider}}:admin
subjects:
  - kind: Group
    name: {{ .group_prefix }}:{{ .group_name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end}}
{{- range .Values.role_bindings.developers}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc:{{.provider}}:developers
subjects:
  - kind: Group
    name: {{ .group_prefix }}:{{ .group_name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:basic-user
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- range .Values.role_bindings.audience }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc:{{.provider}}:audience
subjects:
  - kind: Group
    name: {{ .group_prefix }}:{{ .group_name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
{{- end }}