apiVersion: v2
name: gitea
description: Chart tracks compatible versions of gitea

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: gitea
    version: 8.3.0
    repository: https://dl.gitea.io/charts/