apiVersion: v1
kind: Service
metadata:
  labels:
    app: harbor
  name: harbor-portal-remote
  namespace: {{ .Release.Namespace }}
  annotations:
    io.cilium/global-service: 'true'
    service.cilium.io/affinity: "remote"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: harbor
    component: portal
    release: harbor
  type: ClusterIP

