cluster:
  project:
    metadata_name: saturn
    destination_name: in-cluster
    destination_server: https://kubernetes.default.svc
  application:
    metadata_name: saturn
    destination_name: in-cluster
    destination_namespace: "*"
    project: saturn
    source_path: saturn/argo
    source_repo_url: http://gitea-http.gitea:3000/gocy/saturn.git
argo-cd:
  dex:
    enabled: false
  configs:
    repositories:
      gitea:
        url: http://gitea-http.gitea:3000/gocy/{{ constellation }}.git
    cm:
      url: https://{{ argocd_fqdn }}
      oidc.config: |
        name: dex
        issuer: https://{{ bouncer_fqdn }}
        clientID: argocd
        clientSecret: {{ client_secret }}
        requestedScopes: ["openid", "profile", "email", "groups"]
      params:
        server.insecure: true

  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-gcp
        external-dns.alpha.kubernetes.io/hostname: {{ argocd_fqdn }}
        nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, x-auth-request-access-token"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/server-snippet: |
          proxy_ssl_verify off;
      ingressClassName: "nginx"
      hosts:
        - {{ argocd_fqdn }}
      tls:
        - secretName: tls.{{ argocd_fqdn }}
          hosts:
            - {{ argocd_fqdn }}
